version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cloudy-port
    depends_on:
      - portfolio

  portfolio:
    build:
      context: .
    container_name: cloudy-portfolio
    environment:
      - DB_HOST=db
      - DB_USER=root
      - MYSQL_ROOT_PASSWORD="root@123"
      - DB_NAME=portfolio_db
    networks:
      - cloudy-port
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  db:
    image: mysql
    container_name: sql
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=portfolio_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - cloudy-port
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  
  # --- MONITORING STACK ---
  node-exporter:
    image: prom/node-exporter:latest
    container_name: cloudy-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    ports:
      - "9100:9100"
    networks:
      - cloudy-port

  prometheus:
    image: prom/prometheus:latest
    container_name: cloudy-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cloudy-port

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: cloudy-grafana
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - prometheus
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  #   networks:
  #     - cloudy-port

  grafana:
    image: grafana/grafana:latest
    container_name: cloudy-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=mahdeeali1111@gmail.com
      - GF_SMTP_PASSWORD=udvg wjsz eabh zhvp  # <--- Replace with your 16-character App Password
      - GF_SMTP_FROM_ADDRESS=mahdeeali1111@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Monitoring
      - GF_SMTP_STARTTLS_POLICY=OpportunityIfAvailable
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - cloudy-port

volumes:
  mysql-data:
  grafana-storage:

networks:
  cloudy-port:
  